# Лабораторна робота №4 — NumPy (Варіант 12)

## Імпорт бібліотек

In [1]:
import numpy as np
import time

## Завдання варіанта №12
Необхідно виконати вправи: **2, 3, 5, 14, 17, 18, 19, 20, 21**, а також розв'язати систему рівнянь та обчислити матричний вираз.

## Вправа 2
Створити матрицю розміром *n × n*, заповнену у шаховому порядку.

In [2]:

def task_2_numpy(n):
    a = np.zeros((n, n), dtype=int)
    a[::2, 1::2] = 1
    a[1::2, ::2] = 1
    return a

def task_2_loop(n):
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append((i + j) % 2)
        matrix.append(row)
    return np.array(matrix)


In [3]:
task_2_numpy(5)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [4]:
task_2_loop(5)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

## Вправа 3
Сформувати матрицю *n × m*, у якій кожний *r*-й рядок і *c*-й стовпець містять нулі.

In [5]:

def task_3_numpy(n, m, r, c):
    a = np.ones((n, m), int)
    a[::r, :] = 0
    a[:, ::c] = 0
    return a

def task_3_loop(n, m, r, c):
    result = []
    for i in range(n):
        row = []
        for j in range(m):
            if i % r == 0 or j % c == 0:
                row.append(0)
            else:
                row.append(1)
        result.append(row)
    return np.array(result)


In [6]:
task_3_numpy(6, 7, 2, 3)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0]])

In [7]:
task_3_loop(6, 7, 2, 3)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0]])

## Вправа 5
У парних рядках матриці *n × n* розмістити одиниці, в інших — нулі.

In [8]:

def task_5_numpy(n):
    a = np.zeros((n, n), int)
    a[::2] = 1
    return a

def task_5_loop(n):
    matrix = []
    for i in range(n):
        matrix.append([1]*n if i % 2 == 0 else [0]*n)
    return np.array(matrix)


In [9]:
task_5_numpy(5)

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [10]:
task_5_loop(5)

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

## Вправа 14
Створити шахову матрицю 8×8, використовуючи `numpy.tile()`.

In [11]:

def task_14_numpy():
    base = np.array([[0,1],[1,0]])
    return np.tile(base, (4,4))

def task_14_loop():
    matrix = []
    for i in range(8):
        row = []
        for j in range(8):
            row.append((i + j) % 2)
        matrix.append(row)
    return np.array(matrix)


In [12]:
task_14_numpy()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [13]:
task_14_loop()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Вправа 17
У векторі від 0 до n змінити знак значень, що < n/2 або > 3n/4.

In [14]:

def task_17_numpy(n):
    a = np.arange(0, n+1)
    a[a < n/2] *= -1
    a[a > 3*n/4] *= -1
    return a

def task_17_loop(n):
    result = []
    for x in range(n+1):
        if x < n/2 or x > 3*n/4:
            result.append(-x)
        else:
            result.append(x)
    return np.array(result)


In [15]:
task_17_numpy(10)

array([  0,  -1,  -2,  -3,  -4,   5,   6,   7,  -8,  -9, -10])

In [16]:
task_17_loop(10)

array([  0,  -1,  -2,  -3,  -4,   5,   6,   7,  -8,  -9, -10])

## Вправа 18
Згенерувати вектор випадкових чисел і визначити кількість унікальних.

In [17]:

def task_18_numpy(n):
    a = np.random.randint(0, 100, n)
    return a, len(np.unique(a))

def task_18_loop(n):
    import random
    a = [random.randint(0,99) for _ in range(n)]
    return np.array(a), len(set(a))


In [18]:
task_18_numpy(20)

(array([15,  6, 80,  7, 95, 94, 76, 11, 93, 73, 74,  8, 16, 22, 37, 48, 94,
        30, 78,  1]),
 19)

In [19]:
task_18_loop(20)

(array([72, 99, 29, 40, 70, 81, 65, 59, 70, 51, 34, 69, 74, 99, 85,  3, 26,
        70, 15, 59]),
 16)

## Вправа 19
Сформувати вектор із рівномірно розташованих значень на інтервалі (0, 1).

In [20]:

def task_19_numpy(n):
    a = np.linspace(0,1,n+2)[1:-1]
    return np.round(a, 3)

def task_19_loop(n):
    return np.array([round(i/(n+1), 3) for i in range(1, n+1)])


In [21]:
task_19_numpy(10)

array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818,
       0.909])

In [22]:
task_19_loop(10)

array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818,
       0.909])

## Вправа 20
Замінити максимальний елемент випадкового вектора на нуль.

In [23]:

def task_20_numpy(n):
    a = np.random.rand(n)
    b = a.copy()
    b[b.argmax()] = 0
    return a, b

def task_20_loop(n):
    import random
    a = [random.random() for _ in range(n)]
    b = a.copy()
    mx = max(a)
    b[a.index(mx)] = 0
    return np.array(a), np.array(b)


In [24]:
task_20_numpy(5)

(array([0.70336287, 0.12070362, 0.82614359, 0.7211148 , 0.92437098]),
 array([0.70336287, 0.12070362, 0.82614359, 0.7211148 , 0.        ]))

In [25]:
task_20_loop(5)

(array([0.82713835, 0.14742267, 0.31750221, 0.62468335, 0.81753026]),
 array([0.        , 0.14742267, 0.31750221, 0.62468335, 0.81753026]))

## Вправа 21
У матриці *n × n* замінити всі максимальні значення на протилежні.

In [26]:

def task_21_numpy(n, m):
    a = np.random.randint(0, m+1, (n,n))
    b = a.copy()
    maxval = a.max()
    b[b == maxval] = -maxval
    return a, b

def task_21_loop(n, m):
    import random
    a = [[random.randint(0,m) for _ in range(n)] for _ in range(n)]
    maxval = max(max(row) for row in a)
    b = [[-maxval if x==maxval else x for x in row] for row in a]
    return np.array(a), np.array(b)


In [27]:
task_21_numpy(4, 10)

(array([[8, 0, 2, 2],
        [6, 9, 5, 5],
        [4, 3, 1, 4],
        [9, 4, 8, 7]]),
 array([[ 8,  0,  2,  2],
        [ 6, -9,  5,  5],
        [ 4,  3,  1,  4],
        [-9,  4,  8,  7]]))

In [28]:
task_21_loop(4, 10)

(array([[ 5,  9, 10,  5],
        [ 6,  8,  0, 10],
        [ 0,  4,  2, 10],
        [ 9,  5,  3,  0]]),
 array([[  5,   9, -10,   5],
        [  6,   8,   0, -10],
        [  0,   4,   2, -10],
        [  9,   5,   3,   0]]))

## Система лінійних рівнянь
Розвʼязати систему методами: Крамера, оберненої матриці та `numpy.linalg.solve`.

In [29]:

A_s = np.array([
    [2, -1, 1, -1],
    [-1, -1, -1, 0],
    [1, -1, 1, 0],
    [1, -1, -1, 1]
], float)

b_s = np.array([0,1,2,0], float)

def cramer(A, b):
    detA = np.linalg.det(A)
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        M = A.copy()
        M[:, i] = b
        x[i] = np.linalg.det(M) / detA
    return x

x_cramer = cramer(A_s, b_s)
x_inv = np.linalg.inv(A_s).dot(b_s)
x_solve = np.linalg.solve(A_s, b_s)

x_cramer, x_inv, x_solve


(array([-1. , -1.5,  1.5,  1. ]),
 array([-1. , -1.5,  1.5,  1. ]),
 array([-1. , -1.5,  1.5,  1. ]))

## Матричний вираз
Обчислити:
\[(A - A^2) - (B - B^2) + AB\]

In [30]:

A = np.array([[2,3,1],
              [1,2,4],
              [5,3,0]], float)

B = np.array([[2,7,13],
              [1,0,5],
              [5,13,21]], float)

R_numpy = (A - A@A) - (B - B@B) + A@B

def matmul_loop(X, Y):
    n, m = X.shape
    _, k = Y.shape
    R = np.zeros((n,k))
    for i in range(n):
        for j in range(k):
            total = 0
            for t in range(m):
                total += X[i,t] * Y[t,j]
            R[i,j] = total
    return R

A2 = matmul_loop(A,A)
B2 = matmul_loop(B,B)
AB = matmul_loop(A,B)

R_loop = (A - A2) - (B - B2) + AB

R_numpy, R_loop, np.allclose(R_numpy, R_loop)


(array([[ 76., 191., 370.],
        [ 27., 114., 215.],
        [128., 312., 613.]]),
 array([[ 76., 191., 370.],
        [ 27., 114., 215.],
        [128., 312., 613.]]),
 True)